hydra:
  run:
    dir: ${paths.logs}/${now:%Y-%m-%d-%H-%M-%S}_${hydra.job.name}
  sweep:
    dir: ${paths.logs}/${now:%Y-%m-%d-%H-%M-%S}_${hydra.job.name}
    subdir: ${now:%Y-%m-%d-%H-%M-%S}_${hydra.job.override_dirname}
#   hydra_logging:
#     formatters:
#       simple:
#         format: "[%(asctime)s][HYDRA] %(message)s"
#   job_logging:
#     formatters:
#       simple:
#         format: "[%(asctime)s][%(name)s][%(levelname)s]\n%(message)s"

# Paths to outputs (logs, models)
paths:
  logs: /lustre/fsn1/projects/rech/nry/uul79xi/hydra-logs
  latents: /lustre/fsn1/projects/rech/nry/uul79xi/outputs/latents

# Paths to pre-trained models
pretrained_models:
  vdvae: /lustre/fsn1/projects/rech/nry/uul79xi/store/models/vdvae
  vd: /lustre/fsn1/projects/rech/nry/uul79xi/store/models
  sd: /lustre/fsn1/projects/rech/nry/uul79xi/store/models/stable_diffusion